name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # or 'master', adjust based on your repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: firebase deploy --token "1//0gyKmSYKPLw-7CgYIARAAGBASNwF-L9IrNwovgq6caD2mFFVrvWuTHVFMU65WC5HDO_Z6Uk8i_RcUvjtVRoeBIc-bpsGZ5C4iXHU"
